version: '3'
services:
  api:
    image: library/node:14.5
    env_file: .env
    restart: always
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm start
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    image: library/mariadb:10.5.5
    env_file: .env
    restart: always
    volumes:
    - ./var/db/data:/var/lib/mysql
    ports:
      - 3306:3306
